/* ==========================================
   초등 필수 영단어 800
   data.js (1/16)
   1 ~ 50
========================================== */

const WORDS = [
{id:1,word:"a",pronunciation:"어",meaning:"하나의"},
{id:2,word:"about",pronunciation:"어바웃",meaning:"~에 관하여"},
{id:3,word:"across",pronunciation:"어크로스",meaning:"~을 가로질러"},
{id:4,word:"act",pronunciation:"액트",meaning:"행동"},
{id:5,word:"address",pronunciation:"어드레스",meaning:"주소"},
{id:6,word:"afraid",pronunciation:"어프레이드",meaning:"두려워하여"},
{id:7,word:"after",pronunciation:"애프터",meaning:"~후에"},
{id:8,word:"afternoon",pronunciation:"애프터눈",meaning:"오후"},
{id:9,word:"again",pronunciation:"어게인",meaning:"다시"},
{id:10,word:"age",pronunciation:"에이지",meaning:"나이"},
{id:11,word:"ago",pronunciation:"어고",meaning:"~전에"},
{id:12,word:"air",pronunciation:"에어",meaning:"공기"},
{id:13,word:"airport",pronunciation:"에어포트",meaning:"공항"},
{id:14,word:"album",pronunciation:"앨범",meaning:"사진첩"},
{id:15,word:"all",pronunciation:"올",meaning:"모두"},
{id:16,word:"along",pronunciation:"얼롱",meaning:"~을 따라서"},
{id:17,word:"always",pronunciation:"올웨이즈",meaning:"항상"},
{id:18,word:"among",pronunciation:"어몽",meaning:"~사이에서"},
{id:19,word:"and",pronunciation:"앤드",meaning:"그리고"},
{id:20,word:"angry",pronunciation:"앵그리",meaning:"성난"},
{id:21,word:"animal",pronunciation:"애니멀",meaning:"동물"},
{id:22,word:"answer",pronunciation:"앤서",meaning:"대답"},
{id:23,word:"any",pronunciation:"애니",meaning:"어떤"},
{id:24,word:"apartment",pronunciation:"어파트먼트",meaning:"아파트"},
{id:25,word:"apple",pronunciation:"애플",meaning:"사과"},
{id:26,word:"arm",pronunciation:"암",meaning:"팔"},
{id:27,word:"around",pronunciation:"어라운드",meaning:"~주위에"},
{id:28,word:"arrive",pronunciation:"어라이브",meaning:"도착하다"},
{id:29,word:"as",pronunciation:"애즈",meaning:"~같은, ~로서"},
{id:30,word:"ask",pronunciation:"애스크",meaning:"묻다"},
{id:31,word:"at",pronunciation:"앳",meaning:"~에"},
{id:32,word:"aunt",pronunciation:"앤트",meaning:"이모, 고모"},
{id:33,word:"autumn",pronunciation:"오텀",meaning:"가을"},
{id:34,word:"away",pronunciation:"어웨이",meaning:"떨어져"},
{id:35,word:"baby",pronunciation:"베이비",meaning:"아기"},
{id:36,word:"back",pronunciation:"백",meaning:"뒤에"},
{id:37,word:"bad",pronunciation:"배드",meaning:"나쁜"},
{id:38,word:"bag",pronunciation:"백",meaning:"가방"},
{id:39,word:"ball",pronunciation:"볼",meaning:"공"},
{id:40,word:"balloon",pronunciation:"벌룬",meaning:"풍선"},
{id:41,word:"banana",pronunciation:"버내너",meaning:"바나나"},
{id:42,word:"band",pronunciation:"밴드",meaning:"끈, 악단"},
{id:43,word:"bank",pronunciation:"뱅크",meaning:"은행"},
{id:44,word:"base",pronunciation:"베이스",meaning:"기초"},
{id:45,word:"basket",pronunciation:"배스킷",meaning:"바구니"},
{id:46,word:"bath",pronunciation:"배스",meaning:"목욕"},
{id:47,word:"be",pronunciation:"비",meaning:"~이다"},
{id:48,word:"beach",pronunciation:"비치",meaning:"해변"},
{id:49,word:"bear",pronunciation:"베어",meaning:"곰"},
{id:50,word:"beautiful",pronunciation:"뷰티풀",meaning:"아름다운"},
{id:51,word:"because",pronunciation:"비코즈",meaning:"~때문에"},
{id:52,word:"become",pronunciation:"비컴",meaning:"~이 되다"},
{id:53,word:"bed",pronunciation:"베드",meaning:"침대"},
{id:54,word:"before",pronunciation:"비포",meaning:"~전에"},
{id:55,word:"begin",pronunciation:"비긴",meaning:"시작하다"},
{id:56,word:"behind",pronunciation:"비하인드",meaning:"~뒤에"},
{id:57,word:"bell",pronunciation:"벨",meaning:"종"},
{id:58,word:"below",pronunciation:"빌로우",meaning:"~아래"},
{id:59,word:"bench",pronunciation:"벤치",meaning:"긴 의자"},
{id:60,word:"beside",pronunciation:"비사이드",meaning:"~곁에"},
{id:61,word:"between",pronunciation:"비트윈",meaning:"~사이에"},
{id:62,word:"bicycle",pronunciation:"바이시클",meaning:"자전거"},
{id:63,word:"big",pronunciation:"빅",meaning:"큰"},
{id:64,word:"bird",pronunciation:"버드",meaning:"새"},
{id:65,word:"birthday",pronunciation:"벌스데이",meaning:"생일"},
{id:66,word:"black",pronunciation:"블랙",meaning:"검정색"},
{id:67,word:"blow",pronunciation:"블로우",meaning:"불다"},
{id:68,word:"blue",pronunciation:"블루",meaning:"푸른"},
{id:69,word:"board",pronunciation:"보드",meaning:"판자"},
{id:70,word:"boat",pronunciation:"보트",meaning:"배"},
{id:71,word:"body",pronunciation:"바디",meaning:"몸"},
{id:72,word:"book",pronunciation:"북",meaning:"책"},
{id:73,word:"bottle",pronunciation:"바틀",meaning:"병"},
{id:74,word:"bowl",pronunciation:"볼",meaning:"사발"},
{id:75,word:"box",pronunciation:"박스",meaning:"상자"},
{id:76,word:"boy",pronunciation:"보이",meaning:"소년"},
{id:77,word:"bread",pronunciation:"브레드",meaning:"빵"},
{id:78,word:"break",pronunciation:"브레이크",meaning:"깨뜨리다"},
{id:79,word:"breakfast",pronunciation:"브렉퍼스트",meaning:"아침식사"},
{id:80,word:"bridge",pronunciation:"브리지",meaning:"다리"},
{id:81,word:"bright",pronunciation:"브라이트",meaning:"밝은"},
{id:82,word:"bring",pronunciation:"브링",meaning:"가져오다"},
{id:83,word:"brother",pronunciation:"브라더",meaning:"형제"},
{id:84,word:"brown",pronunciation:"브라운",meaning:"갈색"},
{id:85,word:"brush",pronunciation:"브러시",meaning:"솔"},
{id:86,word:"build",pronunciation:"빌드",meaning:"건설하다"},
{id:87,word:"burn",pronunciation:"번",meaning:"불타다"},
{id:88,word:"bus",pronunciation:"버스",meaning:"버스"},
{id:89,word:"busy",pronunciation:"비지",meaning:"바쁜"},
{id:90,word:"but",pronunciation:"벗",meaning:"그러나"},
{id:91,word:"butter",pronunciation:"버터",meaning:"버터"},
{id:92,word:"button",pronunciation:"버튼",meaning:"단추"},
{id:93,word:"buy",pronunciation:"바이",meaning:"사다"},
{id:94,word:"by",pronunciation:"바이",meaning:"~옆에"},
{id:95,word:"bye",pronunciation:"바이",meaning:"안녕"},
{id:96,word:"calendar",pronunciation:"캘린더",meaning:"달력"},
{id:97,word:"cake",pronunciation:"케이크",meaning:"케이크"},
{id:98,word:"call",pronunciation:"콜",meaning:"부르다"},
{id:99,word:"camera",pronunciation:"카메라",meaning:"사진기"},
{id:100,word:"camp",pronunciation:"캠프",meaning:"야영지"},
{id:101,word:"can",pronunciation:"캔",meaning:"~할 수 있다"},
{id:102,word:"candle",pronunciation:"캔들",meaning:"양초"},
{id:103,word:"candy",pronunciation:"캔디",meaning:"사탕"},
{id:104,word:"cap",pronunciation:"캡",meaning:"모자"},
{id:105,word:"capital",pronunciation:"캐피털",meaning:"수도, 대문자"},
{id:106,word:"captain",pronunciation:"캡틴",meaning:"우두머리"},
{id:107,word:"car",pronunciation:"카",meaning:"자동차"},
{id:108,word:"card",pronunciation:"카드",meaning:"카드"},
{id:109,word:"care",pronunciation:"케어",meaning:"걱정하다, 돌보다"},
{id:110,word:"carry",pronunciation:"캐리",meaning:"나르다"},
{id:111,word:"case",pronunciation:"케이스",meaning:"경우"},
{id:112,word:"cassette",pronunciation:"커세트",meaning:"카세트"},
{id:113,word:"cat",pronunciation:"캣",meaning:"고양이"},
{id:114,word:"catch",pronunciation:"캐치",meaning:"붙잡다"},
{id:115,word:"ceiling",pronunciation:"실링",meaning:"천장"},
{id:116,word:"center",pronunciation:"센터",meaning:"중앙"},
{id:117,word:"chair",pronunciation:"체어",meaning:"의자"},
{id:118,word:"chalk",pronunciation:"초크",meaning:"분필"},
{id:119,word:"chance",pronunciation:"챈스",meaning:"기회"},
{id:120,word:"change",pronunciation:"체인지",meaning:"바꾸다"},
{id:121,word:"cheap",pronunciation:"칩",meaning:"값싼"},
{id:122,word:"cheese",pronunciation:"치즈",meaning:"치즈"},
{id:123,word:"chicken",pronunciation:"치킨",meaning:"닭"},
{id:124,word:"child",pronunciation:"차일드",meaning:"어린이"},
{id:125,word:"chopstick",pronunciation:"찹스틱",meaning:"젓가락"},
{id:126,word:"church",pronunciation:"처치",meaning:"교회"},
{id:127,word:"circle",pronunciation:"서클",meaning:"원"},
{id:128,word:"city",pronunciation:"시티",meaning:"도시"},
{id:129,word:"class",pronunciation:"클래스",meaning:"학급"},
{id:130,word:"classmate",pronunciation:"클래스메이트",meaning:"반 친구"},
{id:131,word:"clean",pronunciation:"클린",meaning:"깨끗한"},
{id:132,word:"climb",pronunciation:"클라임",meaning:"오르다"},
{id:133,word:"clock",pronunciation:"클락",meaning:"시계"},
{id:134,word:"close",pronunciation:"클로즈",meaning:"닫다"},
{id:135,word:"clothes",pronunciation:"클로우즈",meaning:"옷"},
{id:136,word:"cloud",pronunciation:"클라우드",meaning:"구름"},
{id:137,word:"club",pronunciation:"클럽",meaning:"클럽"},
{id:138,word:"coat",pronunciation:"코트",meaning:"코트"},
{id:139,word:"coffee",pronunciation:"커피",meaning:"커피"},
{id:140,word:"coin",pronunciation:"코인",meaning:"동전"},
{id:141,word:"cold",pronunciation:"콜드",meaning:"추운"},
{id:142,word:"color",pronunciation:"컬러",meaning:"색깔"},
{id:143,word:"come",pronunciation:"컴",meaning:"오다"},
{id:144,word:"computer",pronunciation:"컴퓨터",meaning:"컴퓨터"},
{id:145,word:"cook",pronunciation:"쿡",meaning:"요리하다"},
{id:146,word:"cool",pronunciation:"쿨",meaning:"시원한"},
{id:147,word:"copy",pronunciation:"카피",meaning:"사본, 베끼다"},
{id:148,word:"corner",pronunciation:"코너",meaning:"모퉁이"},
{id:149,word:"count",pronunciation:"카운트",meaning:"세다"},
{id:150,word:"country",pronunciation:"컨트리",meaning:"나라, 국가"},
{id:151,word:"course",pronunciation:"코스",meaning:"과정"},
{id:152,word:"cousin",pronunciation:"커즌",meaning:"사촌"},
{id:153,word:"cover",pronunciation:"커버",meaning:"덮다"},
{id:154,word:"cow",pronunciation:"카우",meaning:"암소"},
{id:155,word:"crayon",pronunciation:"크레이언",meaning:"크레용"},
{id:156,word:"cream",pronunciation:"크림",meaning:"크림"},
{id:157,word:"cross",pronunciation:"크로스",meaning:"가로지르다"},
{id:158,word:"cry",pronunciation:"크라이",meaning:"울다"},
{id:159,word:"cup",pronunciation:"컵",meaning:"컵"},
{id:160,word:"dad",pronunciation:"대드",meaning:"아빠, 아버지"},
{id:161,word:"dance",pronunciation:"댄스",meaning:"춤추다"},
{id:162,word:"danger",pronunciation:"데인저",meaning:"위험"},
{id:163,word:"dark",pronunciation:"다크",meaning:"어두운"},
{id:164,word:"date",pronunciation:"데이트",meaning:"날짜"},
{id:165,word:"daughter",pronunciation:"도터",meaning:"딸"},
{id:166,word:"day",pronunciation:"데이",meaning:"낮, 하루"},
{id:167,word:"dead",pronunciation:"데드",meaning:"죽은"},
{id:168,word:"deep",pronunciation:"딥",meaning:"깊은"},
{id:169,word:"dear",pronunciation:"디어",meaning:"존경하는"},
{id:170,word:"desk",pronunciation:"데스크",meaning:"책상"},
{id:171,word:"dial",pronunciation:"다이얼",meaning:"다이얼"},
{id:172,word:"diary",pronunciation:"다이어리",meaning:"일기"},
{id:173,word:"dictionary",pronunciation:"딕셔너리",meaning:"사전"},
{id:174,word:"die",pronunciation:"다이",meaning:"죽다"},
{id:175,word:"dinner",pronunciation:"디너",meaning:"저녁"},
{id:176,word:"dirty",pronunciation:"더티",meaning:"더러운"},
{id:177,word:"dish",pronunciation:"디시",meaning:"큰 접시"},
{id:178,word:"do",pronunciation:"두",meaning:"하다"},
{id:179,word:"doctor",pronunciation:"닥터",meaning:"의사"},
{id:180,word:"dog",pronunciation:"도그",meaning:"개"},
{id:181,word:"doll",pronunciation:"돌",meaning:"인형"},
{id:182,word:"dollar",pronunciation:"달러",meaning:"달러"},
{id:183,word:"dolphin",pronunciation:"돌핀",meaning:"돌고래"},
{id:184,word:"door",pronunciation:"도어",meaning:"문"},
{id:185,word:"down",pronunciation:"다운",meaning:"아래에"},
{id:186,word:"draw",pronunciation:"드로",meaning:"그리다"},
{id:187,word:"dream",pronunciation:"드림",meaning:"꿈"},
{id:188,word:"dress",pronunciation:"드레스",meaning:"드레스"},
{id:189,word:"drink",pronunciation:"드링크",meaning:"마시다"},
{id:190,word:"drive",pronunciation:"드라이브",meaning:"운전하다"},
{id:191,word:"drop",pronunciation:"드롭",meaning:"떨어지다, 방울"},
{id:192,word:"drum",pronunciation:"드럼",meaning:"북"},
{id:193,word:"dry",pronunciation:"드라이",meaning:"마른"},
{id:194,word:"duck",pronunciation:"덕",meaning:"오리"},
{id:195,word:"ear",pronunciation:"이어",meaning:"귀"},
{id:196,word:"early",pronunciation:"얼리",meaning:"일찍"},
{id:197,word:"earth",pronunciation:"어스",meaning:"지구"},
{id:198,word:"east",pronunciation:"이스트",meaning:"동쪽"},
{id:199,word:"easy",pronunciation:"이지",meaning:"쉬운"},
{id:200,word:"eat",pronunciation:"잇",meaning:"먹다"},
{id:201,word:"egg",pronunciation:"에그",meaning:"계란"},
{id:202,word:"empty",pronunciation:"엠프티",meaning:"텅 빈"},
{id:203,word:"end",pronunciation:"엔드",meaning:"끝"},
{id:204,word:"engine",pronunciation:"엔진",meaning:"엔진"},
{id:205,word:"enjoy",pronunciation:"인조이",meaning:"즐기다"},
{id:206,word:"enough",pronunciation:"이너프",meaning:"충분한"},
{id:207,word:"eraser",pronunciation:"이레이저",meaning:"지우개"},
{id:208,word:"evening",pronunciation:"이브닝",meaning:"저녁"},
{id:209,word:"every",pronunciation:"에브리",meaning:"모든, 모두의"},
{id:210,word:"example",pronunciation:"이그잼플",meaning:"예, 보기"},
{id:211,word:"excellent",pronunciation:"엑설런트",meaning:"뛰어난"},
{id:212,word:"excite",pronunciation:"익사이트",meaning:"흥분시키다"},
{id:213,word:"excuse",pronunciation:"익스큐즈",meaning:"용서하다"},
{id:214,word:"exercise",pronunciation:"엑서사이즈",meaning:"연습"},
{id:215,word:"eye",pronunciation:"아이",meaning:"눈"},
{id:216,word:"face",pronunciation:"페이스",meaning:"얼굴"},
{id:217,word:"fact",pronunciation:"팩트",meaning:"사실"},
{id:218,word:"fair",pronunciation:"페어",meaning:"공정한"},
{id:219,word:"fall",pronunciation:"폴",meaning:"가을, 떨어지다"},
{id:220,word:"family",pronunciation:"패밀리",meaning:"가족"},
{id:221,word:"far",pronunciation:"파",meaning:"멀리 떨어진"},
{id:222,word:"farm",pronunciation:"팜",meaning:"농장"},
{id:223,word:"fast",pronunciation:"패스트",meaning:"빠른"},
{id:224,word:"fat",pronunciation:"팻",meaning:"살찐"},
{id:225,word:"famous",pronunciation:"페이머스",meaning:"유명한"},
{id:226,word:"father",pronunciation:"파더",meaning:"아버지"},
{id:227,word:"feel",pronunciation:"필",meaning:"느끼다"},
{id:228,word:"few",pronunciation:"퓨",meaning:"다소 적은"},
{id:229,word:"field",pronunciation:"필드",meaning:"들판, 경기장"},
{id:230,word:"fight",pronunciation:"파이트",meaning:"싸움"},
{id:231,word:"fill",pronunciation:"필",meaning:"채우다"},
{id:232,word:"film",pronunciation:"필름",meaning:"필름"},
{id:233,word:"find",pronunciation:"파인드",meaning:"찾다"},
{id:234,word:"fine",pronunciation:"파인",meaning:"좋은, 맑은"},
{id:235,word:"finger",pronunciation:"핑거",meaning:"손가락"},
{id:236,word:"finish",pronunciation:"피니시",meaning:"끝내다"},
{id:237,word:"fire",pronunciation:"파이어",meaning:"불"},
{id:238,word:"fish",pronunciation:"피시",meaning:"물고기, 낚시하다"},
{id:239,word:"fix",pronunciation:"픽스",meaning:"고정시키다"},
{id:240,word:"flag",pronunciation:"플래그",meaning:"깃발"},
{id:241,word:"floor",pronunciation:"플로어",meaning:"마루"},
{id:242,word:"flower",pronunciation:"플라워",meaning:"꽃"},
{id:243,word:"fly",pronunciation:"플라이",meaning:"날다"},
{id:244,word:"follow",pronunciation:"팔로우",meaning:"뒤를 따르다"},
{id:245,word:"food",pronunciation:"푸드",meaning:"음식"},
{id:246,word:"fool",pronunciation:"풀",meaning:"바보"},
{id:247,word:"foot",pronunciation:"풋",meaning:"발"},
{id:248,word:"for",pronunciation:"포",meaning:"~을 위하여, ~동안"},
{id:249,word:"forget",pronunciation:"포겟",meaning:"잊다"},
{id:250,word:"fork",pronunciation:"포크",meaning:"포크"},
{id:251,word:"free",pronunciation:"프리",meaning:"자유로운"},
{id:252,word:"fresh",pronunciation:"프레시",meaning:"신선한"},
{id:253,word:"friend",pronunciation:"프렌드",meaning:"친구"},
{id:254,word:"from",pronunciation:"프럼",meaning:"~로부터"},
{id:255,word:"front",pronunciation:"프런트",meaning:"앞, 정면"},
{id:256,word:"fruit",pronunciation:"프루트",meaning:"과일"},
{id:257,word:"full",pronunciation:"풀",meaning:"가득 찬"},
{id:258,word:"fun",pronunciation:"펀",meaning:"즐거움"},
{id:259,word:"game",pronunciation:"게임",meaning:"놀이"},
{id:260,word:"garden",pronunciation:"가든",meaning:"정원"},
{id:261,word:"gas",pronunciation:"개스",meaning:"가스, 휘발유"},
{id:262,word:"gate",pronunciation:"게이트",meaning:"문"},
{id:263,word:"gentle",pronunciation:"젠틀",meaning:"온화한"},
{id:264,word:"get",pronunciation:"겟",meaning:"얻다"},
{id:265,word:"girl",pronunciation:"걸",meaning:"소녀"},
{id:266,word:"give",pronunciation:"기브",meaning:"주다"},
{id:267,word:"glad",pronunciation:"글래드",meaning:"기쁜"},
{id:268,word:"glass",pronunciation:"글래스",meaning:"유리, 컵"},
{id:269,word:"glove",pronunciation:"글러브",meaning:"장갑"},
{id:270,word:"go",pronunciation:"고",meaning:"가다"},
{id:271,word:"god",pronunciation:"갓",meaning:"신, 하느님"},
{id:272,word:"gold",pronunciation:"골드",meaning:"금"},
{id:273,word:"good",pronunciation:"굿",meaning:"좋은"},
{id:274,word:"grandmother",pronunciation:"그랜드마더",meaning:"할머니"},
{id:275,word:"grape",pronunciation:"그레이프",meaning:"포도"},
{id:276,word:"grass",pronunciation:"그래스",meaning:"풀, 잔디"},
{id:277,word:"gray",pronunciation:"그레이",meaning:"회색"},
{id:278,word:"great",pronunciation:"그레이트",meaning:"큰"},
{id:279,word:"green",pronunciation:"그린",meaning:"녹색"},
{id:280,word:"ground",pronunciation:"그라운드",meaning:"땅, 기초"},
{id:281,word:"group",pronunciation:"그룹",meaning:"단체"},
{id:282,word:"grow",pronunciation:"그로우",meaning:"성장하다"},
{id:283,word:"guitar",pronunciation:"기타",meaning:"기타(악기)"},
{id:284,word:"hair",pronunciation:"헤어",meaning:"머리카락"},
{id:285,word:"half",pronunciation:"하프",meaning:"절반"},
{id:286,word:"hall",pronunciation:"홀",meaning:"회관, 넓은 방"},
{id:287,word:"hamburger",pronunciation:"햄버거",meaning:"햄버거"},
{id:288,word:"hand",pronunciation:"핸드",meaning:"손"},
{id:289,word:"handle",pronunciation:"핸들",meaning:"손잡이"},
{id:290,word:"happen",pronunciation:"해픈",meaning:"발생하다"},
{id:291,word:"happy",pronunciation:"해피",meaning:"행복한"},
{id:292,word:"hard",pronunciation:"하드",meaning:"단단한, 열심히"},
{id:293,word:"hat",pronunciation:"햇",meaning:"모자"},
{id:294,word:"hate",pronunciation:"헤이트",meaning:"미워하다"},
{id:295,word:"have",pronunciation:"해브",meaning:"가지고 있다"},
{id:296,word:"he",pronunciation:"히",meaning:"그, 남자"},
{id:297,word:"head",pronunciation:"헤드",meaning:"머리"},
{id:298,word:"hear",pronunciation:"히어",meaning:"듣다"},
{id:299,word:"heart",pronunciation:"하트",meaning:"마음, 심장"},
{id:300,word:"heavy",pronunciation:"헤비",meaning:"무거운"},
{id:301,word:"hello",pronunciation:"헬로",meaning:"여보세요"},
{id:302,word:"help",pronunciation:"헬프",meaning:"돕다"},
{id:303,word:"hen",pronunciation:"헨",meaning:"암탉"},
{id:304,word:"here",pronunciation:"히어",meaning:"여기에서"},
{id:305,word:"hi",pronunciation:"하이",meaning:"안녕하세요"},
{id:306,word:"hide",pronunciation:"하이드",meaning:"숨기다"},
{id:307,word:"high",pronunciation:"하이",meaning:"높은"},
{id:308,word:"hiking",pronunciation:"하이킹",meaning:"하이킹"},
{id:309,word:"hill",pronunciation:"힐",meaning:"언덕"},
{id:310,word:"hit",pronunciation:"힛",meaning:"때리다"},
{id:311,word:"hold",pronunciation:"홀드",meaning:"잡다"},
{id:312,word:"hole",pronunciation:"홀",meaning:"구멍"},
{id:313,word:"holiday",pronunciation:"할러데이",meaning:"휴일"},
{id:314,word:"home",pronunciation:"홈",meaning:"집"},
{id:315,word:"hope",pronunciation:"호프",meaning:"희망"},
{id:316,word:"hose",pronunciation:"호즈",meaning:"호스"},
{id:317,word:"curtain",pronunciation:"커튼",meaning:"커튼"},
{id:318,word:"cut",pronunciation:"컷",meaning:"자르다"},
{id:319,word:"horse",pronunciation:"호스",meaning:"말"},
{id:320,word:"hospital",pronunciation:"하스피털",meaning:"병원"},
{id:321,word:"hot",pronunciation:"핫",meaning:"뜨거운"},
{id:322,word:"hotel",pronunciation:"호텔",meaning:"호텔"},
{id:323,word:"hour",pronunciation:"아워",meaning:"시간"},
{id:324,word:"house",pronunciation:"하우스",meaning:"집"},
{id:325,word:"how",pronunciation:"하우",meaning:"어떻게"},
{id:326,word:"hundred",pronunciation:"헌드레드",meaning:"백(100)"},
{id:327,word:"hungry",pronunciation:"헝그리",meaning:"배고픈"},
{id:328,word:"hurry",pronunciation:"허리",meaning:"서두르다"},
{id:329,word:"hurt",pronunciation:"허트",meaning:"다치게 하다"},
{id:330,word:"I",pronunciation:"아이",meaning:"나"},
{id:331,word:"ice",pronunciation:"아이스",meaning:"얼음"},
{id:332,word:"idea",pronunciation:"아이디어",meaning:"생각"},
{id:333,word:"if",pronunciation:"이프",meaning:"만약"},
{id:334,word:"ill",pronunciation:"일",meaning:"병든"},
{id:335,word:"in",pronunciation:"인",meaning:"~속"},
{id:336,word:"ink",pronunciation:"잉크",meaning:"잉크"},
{id:337,word:"interest",pronunciation:"인터레스트",meaning:"흥미"},
{id:338,word:"into",pronunciation:"인투",meaning:"~속으로"},
{id:339,word:"introduce",pronunciation:"인트러듀스",meaning:"소개하다"},
{id:340,word:"island",pronunciation:"아일랜드",meaning:"섬"},
{id:341,word:"it",pronunciation:"잇",meaning:"그것"},
{id:342,word:"job",pronunciation:"잡",meaning:"직업"},
{id:343,word:"join",pronunciation:"조인",meaning:"가입하다"},
{id:344,word:"juice",pronunciation:"주스",meaning:"주스"},
{id:345,word:"jump",pronunciation:"점프",meaning:"뛰어오르다"},
{id:346,word:"jungle",pronunciation:"정글",meaning:"밀림지대"},
{id:347,word:"just",pronunciation:"저스트",meaning:"오직, 겨우"},
{id:348,word:"keep",pronunciation:"킵",meaning:"지키다, 유지하다"},
{id:349,word:"key",pronunciation:"키",meaning:"열쇠"},
{id:350,word:"kick",pronunciation:"킥",meaning:"차다"},
{id:351,word:"kid",pronunciation:"키드",meaning:"아이"},
{id:352,word:"kill",pronunciation:"킬",meaning:"죽이다"},
{id:353,word:"kind",pronunciation:"카인드",meaning:"친절한, 종류"},
{id:354,word:"king",pronunciation:"킹",meaning:"왕"},
{id:355,word:"kitchen",pronunciation:"키친",meaning:"부엌"},
{id:356,word:"knee",pronunciation:"니",meaning:"무릎"},
{id:357,word:"knife",pronunciation:"나이프",meaning:"칼"},
{id:358,word:"knock",pronunciation:"낙",meaning:"두드리다"},
{id:359,word:"know",pronunciation:"노우",meaning:"알다"},
{id:360,word:"lady",pronunciation:"레이디",meaning:"숙녀"},
{id:361,word:"lake",pronunciation:"레이크",meaning:"호수"},
{id:362,word:"lamp",pronunciation:"램프",meaning:"등불"},
{id:363,word:"land",pronunciation:"랜드",meaning:"땅"},
{id:364,word:"large",pronunciation:"라지",meaning:"큰, 넓은"},
{id:365,word:"last",pronunciation:"라스트",meaning:"마지막, 최근"},
{id:366,word:"late",pronunciation:"레이트",meaning:"늦은"},
{id:367,word:"laugh",pronunciation:"래프",meaning:"웃다"},
{id:368,word:"lead",pronunciation:"리드",meaning:"인도하다"},
{id:369,word:"leaf",pronunciation:"리프",meaning:"잎"},
{id:370,word:"learn",pronunciation:"런",meaning:"배우다"},
{id:371,word:"leave",pronunciation:"리브",meaning:"떠나다"},
{id:372,word:"left",pronunciation:"레프트",meaning:"왼쪽"},
{id:373,word:"leg",pronunciation:"레그",meaning:"다리"},
{id:374,word:"lesson",pronunciation:"레슨",meaning:"학과"},
{id:375,word:"let",pronunciation:"렛",meaning:"허락하다"},
{id:376,word:"letter",pronunciation:"레터",meaning:"편지"},
{id:377,word:"library",pronunciation:"라이브러리",meaning:"도서관"},
{id:378,word:"lie",pronunciation:"라이",meaning:"눕다, 거짓말하다"},
{id:379,word:"light",pronunciation:"라이트",meaning:"빛"},
{id:380,word:"like",pronunciation:"라이크",meaning:"좋아하다"},
{id:381,word:"line",pronunciation:"라인",meaning:"선, 줄"},
{id:382,word:"lion",pronunciation:"라이언",meaning:"사자"},
{id:383,word:"lip",pronunciation:"립",meaning:"입술"},
{id:384,word:"list",pronunciation:"리스트",meaning:"목록"},
{id:385,word:"listen",pronunciation:"리슨",meaning:"듣다"},
{id:386,word:"little",pronunciation:"리틀",meaning:"작은"},
{id:387,word:"live",pronunciation:"리브",meaning:"살다, 생생한"},
{id:388,word:"long",pronunciation:"롱",meaning:"긴"},
{id:389,word:"look",pronunciation:"룩",meaning:"바라보다"},
{id:390,word:"lose",pronunciation:"루즈",meaning:"잃다"},
{id:391,word:"lot",pronunciation:"랏",meaning:"많음"},
{id:392,word:"loud",pronunciation:"라우드",meaning:"소리가 큰"},
{id:393,word:"love",pronunciation:"러브",meaning:"사랑하다"},
{id:394,word:"low",pronunciation:"로우",meaning:"낮은"},
{id:395,word:"luck",pronunciation:"럭",meaning:"행운"},
{id:396,word:"lunch",pronunciation:"런치",meaning:"점심식사"},
{id:397,word:"ma'am",pronunciation:"맴",meaning:"아주머니"},
{id:398,word:"mad",pronunciation:"매드",meaning:"미친"},
{id:399,word:"mail",pronunciation:"메일",meaning:"우편"},
{id:400,word:"make",pronunciation:"메이크",meaning:"만들다"},
{id:401,word:"man",pronunciation:"맨",meaning:"사람, 남자"},
{id:402,word:"many",pronunciation:"매니",meaning:"많은"},
{id:403,word:"map",pronunciation:"맵",meaning:"지도"},
{id:404,word:"march",pronunciation:"마치",meaning:"행진, 3월"},
{id:405,word:"market",pronunciation:"마켓",meaning:"상점"},
{id:406,word:"marry",pronunciation:"메리",meaning:"결혼하다"},
{id:407,word:"matter",pronunciation:"매터",meaning:"문제"},
{id:408,word:"may",pronunciation:"메이",meaning:"~해도 좋다, 5월"},
{id:409,word:"meat",pronunciation:"미트",meaning:"고기"},
{id:410,word:"medal",pronunciation:"메달",meaning:"메달"},
{id:411,word:"meet",pronunciation:"밋",meaning:"만나다"},
{id:412,word:"melon",pronunciation:"멜런",meaning:"멜론"},
{id:413,word:"meter",pronunciation:"미터",meaning:"미터"},
{id:414,word:"middle",pronunciation:"미들",meaning:"한가운데"},
{id:415,word:"milk",pronunciation:"밀크",meaning:"우유"},
{id:416,word:"million",pronunciation:"밀리언",meaning:"100만"},
{id:417,word:"minute",pronunciation:"미닛",meaning:"분, 순간"},
{id:418,word:"mirror",pronunciation:"미러",meaning:"거울"},
{id:419,word:"Miss",pronunciation:"미스",meaning:"~양, 호칭"},
{id:420,word:"model",pronunciation:"모델",meaning:"모형"},
{id:421,word:"mom",pronunciation:"맘",meaning:"엄마"},
{id:422,word:"money",pronunciation:"머니",meaning:"돈"},
{id:423,word:"monkey",pronunciation:"멍키",meaning:"원숭이"},
{id:424,word:"month",pronunciation:"먼스",meaning:"달, 개월"},
{id:425,word:"moon",pronunciation:"문",meaning:"달"},
{id:426,word:"morning",pronunciation:"모닝",meaning:"아침"},
{id:427,word:"mother",pronunciation:"마더",meaning:"어머니"},
{id:428,word:"mountain",pronunciation:"마운틴",meaning:"산"},
{id:429,word:"mouth",pronunciation:"마우스",meaning:"입"},
{id:430,word:"move",pronunciation:"무브",meaning:"움직이다"},
{id:431,word:"movie",pronunciation:"무비",meaning:"영화"},
{id:432,word:"Mr.",pronunciation:"미스터",meaning:"~씨"},
{id:433,word:"Mrs.",pronunciation:"미세즈",meaning:"~여사"},
{id:434,word:"much",pronunciation:"머치",meaning:"많은"},
{id:435,word:"music",pronunciation:"뮤직",meaning:"음악"},
{id:436,word:"must",pronunciation:"머스트",meaning:"~해야 한다"},
{id:437,word:"name",pronunciation:"네임",meaning:"이름"},
{id:438,word:"narrow",pronunciation:"내로우",meaning:"좁은"},
{id:439,word:"near",pronunciation:"니어",meaning:"가까운"},
{id:440,word:"neck",pronunciation:"넥",meaning:"목"},
{id:441,word:"need",pronunciation:"니드",meaning:"필요하다"},
{id:442,word:"never",pronunciation:"네버",meaning:"결코 ~않다"},
{id:443,word:"new",pronunciation:"뉴",meaning:"새로운"},
{id:444,word:"news",pronunciation:"뉴스",meaning:"뉴스"},
{id:445,word:"next",pronunciation:"넥스트",meaning:"다음의"},
{id:446,word:"nice",pronunciation:"나이스",meaning:"좋은"},
{id:447,word:"night",pronunciation:"나이트",meaning:"밤"},
{id:448,word:"no",pronunciation:"노",meaning:"아니다, 없다"},
{id:449,word:"noise",pronunciation:"노이즈",meaning:"소음"},
{id:450,word:"north",pronunciation:"노스",meaning:"북쪽"},
{id:451,word:"nose",pronunciation:"노우즈",meaning:"코"},
{id:452,word:"not",pronunciation:"낫",meaning:"아니다"},
{id:453,word:"note",pronunciation:"노트",meaning:"공책"},
{id:454,word:"now",pronunciation:"나우",meaning:"지금"},
{id:455,word:"number",pronunciation:"넘버",meaning:"숫자"},
{id:456,word:"nurse",pronunciation:"널스",meaning:"간호원"},
{id:457,word:"o'clock",pronunciation:"어클락",meaning:"~시 정각"},
{id:458,word:"of",pronunciation:"오브",meaning:"~의"},
{id:459,word:"off",pronunciation:"오프",meaning:"떨어진, 끄다"},
{id:460,word:"office",pronunciation:"오피스",meaning:"사무실"},
{id:461,word:"often",pronunciation:"오픈",meaning:"흔히, 종종"},
{id:462,word:"oh",pronunciation:"오",meaning:"오!"},
{id:463,word:"oil",pronunciation:"오일",meaning:"기름"},
{id:464,word:"okay",pronunciation:"오케이",meaning:"좋아"},
{id:465,word:"old",pronunciation:"올드",meaning:"늙은"},
{id:466,word:"on",pronunciation:"온",meaning:"~위에"},
{id:467,word:"once",pronunciation:"원스",meaning:"한 번"},
{id:468,word:"only",pronunciation:"온리",meaning:"오직"},
{id:469,word:"open",pronunciation:"오픈",meaning:"열린"},
{id:470,word:"or",pronunciation:"오어",meaning:"또는"},
{id:471,word:"orange",pronunciation:"오린지",meaning:"오렌지"},
{id:472,word:"other",pronunciation:"아더",meaning:"그 밖의"},
{id:473,word:"out",pronunciation:"아웃",meaning:"밖에"},
{id:474,word:"over",pronunciation:"오버",meaning:"~위쪽에"},
{id:475,word:"page",pronunciation:"페이지",meaning:"쪽"},
{id:476,word:"paint",pronunciation:"페인트",meaning:"칠하다"},
{id:477,word:"pair",pronunciation:"페어",meaning:"짝"},
{id:478,word:"pants",pronunciation:"팬츠",meaning:"바지"},
{id:479,word:"paper",pronunciation:"페이퍼",meaning:"종이"},
{id:480,word:"pardon",pronunciation:"파든",meaning:"용서하다"},
{id:481,word:"parent",pronunciation:"페어런트",meaning:"부모"},
{id:482,word:"park",pronunciation:"파크",meaning:"공원"},
{id:483,word:"party",pronunciation:"파티",meaning:"파티"},
{id:484,word:"pass",pronunciation:"패스",meaning:"통과하다"},
{id:485,word:"pay",pronunciation:"페이",meaning:"지불하다"},
{id:486,word:"peace",pronunciation:"피스",meaning:"평화"},
{id:487,word:"pear",pronunciation:"페어",meaning:"배"},
{id:488,word:"pen",pronunciation:"펜",meaning:"펜, 만년필"},
{id:489,word:"pencil",pronunciation:"펜슬",meaning:"연필"},
{id:490,word:"people",pronunciation:"피플",meaning:"사람"},
{id:491,word:"piano",pronunciation:"피아노",meaning:"피아노"},
{id:492,word:"pick",pronunciation:"픽",meaning:"따다, 골라내다"},
{id:493,word:"picnic",pronunciation:"피크닉",meaning:"소풍"},
{id:494,word:"picture",pronunciation:"픽처",meaning:"그림"},
{id:495,word:"piece",pronunciation:"피스",meaning:"조각"},
{id:496,word:"pig",pronunciation:"피그",meaning:"돼지"},
{id:497,word:"pilot",pronunciation:"파일럿",meaning:"조종사"},
{id:498,word:"pin",pronunciation:"핀",meaning:"핀"},
{id:499,word:"pine",pronunciation:"파인",meaning:"소나무"},
{id:500,word:"pink",pronunciation:"핑크",meaning:"분홍"},
{id:501,word:"pipe",pronunciation:"파이프",meaning:"파이프"},
{id:502,word:"place",pronunciation:"플레이스",meaning:"장소"},
{id:503,word:"plan",pronunciation:"플랜",meaning:"계획"},
{id:504,word:"plane",pronunciation:"플레인",meaning:"비행기"},
{id:505,word:"plant",pronunciation:"플랜트",meaning:"식물"},
{id:506,word:"play",pronunciation:"플레이",meaning:"놀다"},
{id:507,word:"player",pronunciation:"플레이어",meaning:"선수"},
{id:508,word:"please",pronunciation:"플리즈",meaning:"부디"},
{id:509,word:"pocket",pronunciation:"파켓",meaning:"주머니"},
{id:510,word:"point",pronunciation:"포인트",meaning:"점"},
{id:511,word:"police",pronunciation:"폴리스",meaning:"경찰"},
{id:512,word:"pool",pronunciation:"풀",meaning:"수영장"},
{id:513,word:"poor",pronunciation:"푸어",meaning:"가난한"},
{id:514,word:"popular",pronunciation:"파퓰러",meaning:"인기 있는"},
{id:515,word:"post",pronunciation:"포스트",meaning:"우편"},
{id:516,word:"pot",pronunciation:"팟",meaning:"냄비"},
{id:517,word:"potato",pronunciation:"포테이토",meaning:"감자"},
{id:518,word:"practice",pronunciation:"프랙티스",meaning:"연습"},
{id:519,word:"present",pronunciation:"프레즌트",meaning:"선물"},
{id:520,word:"pretty",pronunciation:"프리티",meaning:"예쁜"},
{id:521,word:"price",pronunciation:"프라이스",meaning:"가격"},
{id:522,word:"problem",pronunciation:"프라블럼",meaning:"문제"},
{id:523,word:"pull",pronunciation:"풀",meaning:"끌다"},
{id:524,word:"push",pronunciation:"푸시",meaning:"밀다"},
{id:525,word:"put",pronunciation:"풋",meaning:"놓다"},
{id:526,word:"queen",pronunciation:"퀸",meaning:"여왕"},
{id:527,word:"question",pronunciation:"퀘스천",meaning:"질문"},
{id:528,word:"quick",pronunciation:"퀵",meaning:"빠른"},
{id:529,word:"quiet",pronunciation:"콰이어트",meaning:"조용한"},
{id:530,word:"rabbit",pronunciation:"래빗",meaning:"토끼"},
{id:531,word:"radio",pronunciation:"레이디오",meaning:"라디오"},
{id:532,word:"rain",pronunciation:"레인",meaning:"비"},
{id:533,word:"rainbow",pronunciation:"레인보우",meaning:"무지개"},
{id:534,word:"read",pronunciation:"리드",meaning:"읽다"},
{id:535,word:"ready",pronunciation:"레디",meaning:"준비된"},
{id:536,word:"red",pronunciation:"레드",meaning:"빨간색"},
{id:537,word:"remember",pronunciation:"리멤버",meaning:"기억하다"},
{id:538,word:"rest",pronunciation:"레스트",meaning:"쉬다"},
{id:539,word:"restaurant",pronunciation:"레스토랑",meaning:"식당"},
{id:540,word:"rice",pronunciation:"라이스",meaning:"쌀"},
{id:541,word:"rich",pronunciation:"리치",meaning:"부유한"},
{id:542,word:"ride",pronunciation:"라이드",meaning:"타다"},
{id:543,word:"right",pronunciation:"라이트",meaning:"오른쪽"},
{id:544,word:"ring",pronunciation:"링",meaning:"반지"},
{id:545,word:"river",pronunciation:"리버",meaning:"강"},
{id:546,word:"road",pronunciation:"로드",meaning:"길"},
{id:547,word:"robot",pronunciation:"로봇",meaning:"로봇"},
{id:548,word:"rock",pronunciation:"락",meaning:"바위"},
{id:549,word:"room",pronunciation:"룸",meaning:"방"},
{id:550,word:"rose",pronunciation:"로즈",meaning:"장미"},
{id:551,word:"round",pronunciation:"라운드",meaning:"둥근"},
{id:552,word:"row",pronunciation:"로우",meaning:"줄"},
{id:553,word:"rub",pronunciation:"럽",meaning:"문지르다"},
{id:554,word:"rule",pronunciation:"룰",meaning:"규칙"},
{id:555,word:"run",pronunciation:"런",meaning:"달리다"},
{id:556,word:"sad",pronunciation:"새드",meaning:"슬픈"},
{id:557,word:"safe",pronunciation:"세이프",meaning:"안전한"},
{id:558,word:"sail",pronunciation:"세일",meaning:"항해하다"},
{id:559,word:"salt",pronunciation:"솔트",meaning:"소금"},
{id:560,word:"same",pronunciation:"세임",meaning:"같은"},
{id:561,word:"sand",pronunciation:"샌드",meaning:"모래"},
{id:562,word:"Saturday",pronunciation:"새터데이",meaning:"토요일"},
{id:563,word:"say",pronunciation:"세이",meaning:"말하다"},
{id:564,word:"school",pronunciation:"스쿨",meaning:"학교"},
{id:565,word:"science",pronunciation:"사이언스",meaning:"과학"},
{id:566,word:"scissors",pronunciation:"시저즈",meaning:"가위"},
{id:567,word:"sea",pronunciation:"씨",meaning:"바다"},
{id:568,word:"season",pronunciation:"시즌",meaning:"계절"},
{id:569,word:"seat",pronunciation:"시트",meaning:"자리"},
{id:570,word:"see",pronunciation:"씨",meaning:"보다"},
{id:571,word:"sell",pronunciation:"셀",meaning:"팔다"},
{id:572,word:"send",pronunciation:"센드",meaning:"보내다"},
{id:573,word:"September",pronunciation:"셉템버",meaning:"9월"},
{id:574,word:"set",pronunciation:"셋",meaning:"놓다"},
{id:575,word:"shake",pronunciation:"셰이크",meaning:"흔들다"},
{id:576,word:"shape",pronunciation:"셰이프",meaning:"모양"},
{id:577,word:"she",pronunciation:"쉬",meaning:"그녀"},
{id:578,word:"sheep",pronunciation:"쉽",meaning:"양"},
{id:579,word:"ship",pronunciation:"쉽",meaning:"배"},
{id:580,word:"shirt",pronunciation:"셔트",meaning:"셔츠"},
{id:581,word:"shoe",pronunciation:"슈",meaning:"신발"},
{id:582,word:"shop",pronunciation:"샵",meaning:"가게"},
{id:583,word:"short",pronunciation:"쇼트",meaning:"짧은"},
{id:584,word:"should",pronunciation:"슈드",meaning:"~해야 한다"},
{id:585,word:"shoulder",pronunciation:"숄더",meaning:"어깨"},
{id:586,word:"show",pronunciation:"쇼",meaning:"보여주다"},
{id:587,word:"shy",pronunciation:"샤이",meaning:"수줍은"},
{id:588,word:"sick",pronunciation:"식",meaning:"아픈"},
{id:589,word:"side",pronunciation:"사이드",meaning:"옆"},
{id:590,word:"sing",pronunciation:"싱",meaning:"노래하다"},
{id:591,word:"sister",pronunciation:"시스터",meaning:"여자 형제"},
{id:592,word:"sit",pronunciation:"싯",meaning:"앉다"},
{id:593,word:"six",pronunciation:"식스",meaning:"6"},
{id:594,word:"size",pronunciation:"사이즈",meaning:"크기"},
{id:595,word:"skate",pronunciation:"스케이트",meaning:"스케이트를 타다"},
{id:596,word:"ski",pronunciation:"스키",meaning:"스키"},
{id:597,word:"skin",pronunciation:"스킨",meaning:"피부"},
{id:598,word:"sky",pronunciation:"스카이",meaning:"하늘"},
{id:599,word:"sleep",pronunciation:"슬립",meaning:"잠을 자다"},
{id:600,word:"slow",pronunciation:"슬로우",meaning:"느린"},
{id:601,word:"small",pronunciation:"스몰",meaning:"작은"},
{id:602,word:"smell",pronunciation:"스멜",meaning:"냄새가 나다"},
{id:603,word:"smile",pronunciation:"스마일",meaning:"미소 짓다"},
{id:604,word:"smoke",pronunciation:"스모크",meaning:"연기"},
{id:605,word:"snake",pronunciation:"스네이크",meaning:"뱀"},
{id:606,word:"snow",pronunciation:"스노우",meaning:"눈"},
{id:607,word:"so",pronunciation:"소우",meaning:"그래서"},
{id:608,word:"sock",pronunciation:"삭",meaning:"양말"},
{id:609,word:"soft",pronunciation:"소프트",meaning:"부드러운"},
{id:610,word:"some",pronunciation:"썸",meaning:"약간의"},
{id:611,word:"son",pronunciation:"선",meaning:"아들"},
{id:612,word:"song",pronunciation:"송",meaning:"노래"},
{id:613,word:"soon",pronunciation:"순",meaning:"곧"},
{id:614,word:"sorry",pronunciation:"쏘리",meaning:"미안한"},
{id:615,word:"sound",pronunciation:"사운드",meaning:"소리"},
{id:616,word:"soup",pronunciation:"수프",meaning:"수프"},
{id:617,word:"south",pronunciation:"사우스",meaning:"남쪽"},
{id:618,word:"space",pronunciation:"스페이스",meaning:"공간"},
{id:619,word:"speak",pronunciation:"스피크",meaning:"말하다"},
{id:620,word:"speed",pronunciation:"스피드",meaning:"속도"},
{id:621,word:"spell",pronunciation:"스펠",meaning:"철자를 말하다"},
{id:622,word:"spend",pronunciation:"스펜드",meaning:"쓰다, 소비하다"},
{id:623,word:"spoon",pronunciation:"스푼",meaning:"숟가락"},
{id:624,word:"sport",pronunciation:"스포트",meaning:"운동"},
{id:625,word:"spring",pronunciation:"스프링",meaning:"봄"},
{id:626,word:"square",pronunciation:"스퀘어",meaning:"정사각형"},
{id:627,word:"stand",pronunciation:"스탠드",meaning:"서다"},
{id:628,word:"star",pronunciation:"스타",meaning:"별"},
{id:629,word:"start",pronunciation:"스타트",meaning:"시작하다"},
{id:630,word:"station",pronunciation:"스테이션",meaning:"역"},
{id:631,word:"stay",pronunciation:"스테이",meaning:"머무르다"},
{id:632,word:"step",pronunciation:"스텝",meaning:"걸음"},
{id:633,word:"stick",pronunciation:"스틱",meaning:"막대기"},
{id:634,word:"still",pronunciation:"스틸",meaning:"여전히"},
{id:635,word:"stone",pronunciation:"스톤",meaning:"돌"},
{id:636,word:"stop",pronunciation:"스탑",meaning:"멈추다"},
{id:637,word:"store",pronunciation:"스토어",meaning:"가게"},
{id:638,word:"story",pronunciation:"스토리",meaning:"이야기"},
{id:639,word:"straight",pronunciation:"스트레이트",meaning:"곧은"},
{id:640,word:"street",pronunciation:"스트리트",meaning:"거리"},
{id:641,word:"strong",pronunciation:"스트롱",meaning:"강한"},
{id:642,word:"student",pronunciation:"스튜던트",meaning:"학생"},
{id:643,word:"study",pronunciation:"스터디",meaning:"공부하다"},
{id:644,word:"subway",pronunciation:"서브웨이",meaning:"지하철"},
{id:645,word:"sugar",pronunciation:"슈거",meaning:"설탕"},
{id:646,word:"summer",pronunciation:"서머",meaning:"여름"},
{id:647,word:"sun",pronunciation:"선",meaning:"태양"},
{id:648,word:"Sunday",pronunciation:"선데이",meaning:"일요일"},
{id:649,word:"supermarket",pronunciation:"슈퍼마켓",meaning:"슈퍼마켓"},
{id:650,word:"sure",pronunciation:"슈어",meaning:"확실한"},
{id:601,word:"small",pronunciation:"스몰",meaning:"작은"},
{id:602,word:"smell",pronunciation:"스멜",meaning:"냄새가 나다"},
{id:603,word:"smile",pronunciation:"스마일",meaning:"미소 짓다"},
{id:604,word:"smoke",pronunciation:"스모크",meaning:"연기"},
{id:605,word:"snake",pronunciation:"스네이크",meaning:"뱀"},
{id:606,word:"snow",pronunciation:"스노우",meaning:"눈"},
{id:607,word:"so",pronunciation:"소우",meaning:"그래서"},
{id:608,word:"sock",pronunciation:"삭",meaning:"양말"},
{id:609,word:"soft",pronunciation:"소프트",meaning:"부드러운"},
{id:610,word:"some",pronunciation:"썸",meaning:"약간의"},
{id:611,word:"son",pronunciation:"선",meaning:"아들"},
{id:612,word:"song",pronunciation:"송",meaning:"노래"},
{id:613,word:"soon",pronunciation:"순",meaning:"곧"},
{id:614,word:"sorry",pronunciation:"쏘리",meaning:"미안한"},
{id:615,word:"sound",pronunciation:"사운드",meaning:"소리"},
{id:616,word:"soup",pronunciation:"수프",meaning:"수프"},
{id:617,word:"south",pronunciation:"사우스",meaning:"남쪽"},
{id:618,word:"space",pronunciation:"스페이스",meaning:"공간"},
{id:619,word:"speak",pronunciation:"스피크",meaning:"말하다"},
{id:620,word:"speed",pronunciation:"스피드",meaning:"속도"},
{id:621,word:"spell",pronunciation:"스펠",meaning:"철자를 말하다"},
{id:622,word:"spend",pronunciation:"스펜드",meaning:"쓰다, 소비하다"},
{id:623,word:"spoon",pronunciation:"스푼",meaning:"숟가락"},
{id:624,word:"sport",pronunciation:"스포트",meaning:"운동"},
{id:625,word:"spring",pronunciation:"스프링",meaning:"봄"},
{id:626,word:"square",pronunciation:"스퀘어",meaning:"정사각형"},
{id:627,word:"stand",pronunciation:"스탠드",meaning:"서다"},
{id:628,word:"star",pronunciation:"스타",meaning:"별"},
{id:629,word:"start",pronunciation:"스타트",meaning:"시작하다"},
{id:630,word:"station",pronunciation:"스테이션",meaning:"역"},
{id:631,word:"stay",pronunciation:"스테이",meaning:"머무르다"},
{id:632,word:"step",pronunciation:"스텝",meaning:"걸음"},
{id:633,word:"stick",pronunciation:"스틱",meaning:"막대기"},
{id:634,word:"still",pronunciation:"스틸",meaning:"여전히"},
{id:635,word:"stone",pronunciation:"스톤",meaning:"돌"},
{id:636,word:"stop",pronunciation:"스탑",meaning:"멈추다"},
{id:637,word:"store",pronunciation:"스토어",meaning:"가게"},
{id:638,word:"story",pronunciation:"스토리",meaning:"이야기"},
{id:639,word:"straight",pronunciation:"스트레이트",meaning:"곧은"},
{id:640,word:"street",pronunciation:"스트리트",meaning:"거리"},
{id:641,word:"strong",pronunciation:"스트롱",meaning:"강한"},
{id:642,word:"student",pronunciation:"스튜던트",meaning:"학생"},
{id:643,word:"study",pronunciation:"스터디",meaning:"공부하다"},
{id:644,word:"subway",pronunciation:"서브웨이",meaning:"지하철"},
{id:645,word:"sugar",pronunciation:"슈거",meaning:"설탕"},
{id:646,word:"summer",pronunciation:"서머",meaning:"여름"},
{id:647,word:"sun",pronunciation:"선",meaning:"태양"},
{id:648,word:"Sunday",pronunciation:"선데이",meaning:"일요일"},
{id:649,word:"supermarket",pronunciation:"슈퍼마켓",meaning:"슈퍼마켓"},
{id:650,word:"sure",pronunciation:"슈어",meaning:"확실한"},
{id:701,word:"train",pronunciation:"트레인",meaning:"기차"},
{id:702,word:"travel",pronunciation:"트래블",meaning:"여행하다"},
{id:703,word:"tree",pronunciation:"트리",meaning:"나무"},
{id:704,word:"trip",pronunciation:"트립",meaning:"여행"},
{id:705,word:"true",pronunciation:"트루",meaning:"참인"},
{id:706,word:"try",pronunciation:"트라이",meaning:"노력하다"},
{id:707,word:"Tuesday",pronunciation:"튜즈데이",meaning:"화요일"},
{id:708,word:"turn",pronunciation:"턴",meaning:"돌다"},
{id:709,word:"TV",pronunciation:"티브이",meaning:"텔레비전"},
{id:710,word:"umbrella",pronunciation:"엄브렐라",meaning:"우산"},
{id:711,word:"uncle",pronunciation:"엉클",meaning:"삼촌"},
{id:712,word:"under",pronunciation:"언더",meaning:"~아래에"},
{id:713,word:"understand",pronunciation:"언더스탠드",meaning:"이해하다"},
{id:714,word:"up",pronunciation:"업",meaning:"위에"},
{id:715,word:"use",pronunciation:"유즈",meaning:"사용하다"},
{id:716,word:"useful",pronunciation:"유스풀",meaning:"유용한"},
{id:717,word:"vacation",pronunciation:"베이케이션",meaning:"방학"},
{id:718,word:"vegetable",pronunciation:"베지터블",meaning:"채소"},
{id:719,word:"very",pronunciation:"베리",meaning:"매우"},
{id:720,word:"village",pronunciation:"빌리지",meaning:"마을"},
{id:721,word:"visit",pronunciation:"비지트",meaning:"방문하다"},
{id:722,word:"voice",pronunciation:"보이스",meaning:"목소리"},
{id:723,word:"wait",pronunciation:"웨이트",meaning:"기다리다"},
{id:724,word:"wake",pronunciation:"웨이크",meaning:"잠에서 깨다"},
{id:725,word:"walk",pronunciation:"워크",meaning:"걷다"},
{id:726,word:"wall",pronunciation:"월",meaning:"벽"},
{id:727,word:"want",pronunciation:"원트",meaning:"원하다"},
{id:728,word:"warm",pronunciation:"웜",meaning:"따뜻한"},
{id:729,word:"wash",pronunciation:"워시",meaning:"씻다"},
{id:730,word:"watch",pronunciation:"와치",meaning:"보다"},
{id:731,word:"water",pronunciation:"워터",meaning:"물"},
{id:732,word:"way",pronunciation:"웨이",meaning:"길"},
{id:733,word:"we",pronunciation:"위",meaning:"우리"},
{id:734,word:"weak",pronunciation:"위크",meaning:"약한"},
{id:735,word:"wear",pronunciation:"웨어",meaning:"입다"},
{id:736,word:"weather",pronunciation:"웨더",meaning:"날씨"},
{id:737,word:"Wednesday",pronunciation:"웬즈데이",meaning:"수요일"},
{id:738,word:"week",pronunciation:"위크",meaning:"주"},
{id:739,word:"welcome",pronunciation:"웰컴",meaning:"환영하다"},
{id:740,word:"well",pronunciation:"웰",meaning:"잘"},
{id:741,word:"west",pronunciation:"웨스트",meaning:"서쪽"},
{id:742,word:"wet",pronunciation:"웻",meaning:"젖은"},
{id:743,word:"what",pronunciation:"왓",meaning:"무엇"},
{id:744,word:"when",pronunciation:"웬",meaning:"언제"},
{id:745,word:"where",pronunciation:"웨어",meaning:"어디"},
{id:746,word:"which",pronunciation:"위치",meaning:"어느 것"},
{id:747,word:"white",pronunciation:"화이트",meaning:"흰색"},
{id:748,word:"who",pronunciation:"후",meaning:"누구"},
{id:749,word:"why",pronunciation:"와이",meaning:"왜"},
{id:750,word:"wide",pronunciation:"와이드",meaning:"넓은"},
{id:751,word:"wife",pronunciation:"와이프",meaning:"아내"},
{id:752,word:"win",pronunciation:"윈",meaning:"이기다"},
{id:753,word:"wind",pronunciation:"윈드",meaning:"바람"},
{id:754,word:"window",pronunciation:"윈도우",meaning:"창문"},
{id:755,word:"winter",pronunciation:"윈터",meaning:"겨울"},
{id:756,word:"with",pronunciation:"위드",meaning:"~와 함께"},
{id:757,word:"woman",pronunciation:"우먼",meaning:"여자"},
{id:758,word:"wonder",pronunciation:"원더",meaning:"궁금해하다"},
{id:759,word:"word",pronunciation:"워드",meaning:"단어"},
{id:760,word:"work",pronunciation:"워크",meaning:"일하다"},
{id:761,word:"worker",pronunciation:"워커",meaning:"노동자"},
{id:762,word:"world",pronunciation:"월드",meaning:"세계"},
{id:763,word:"write",pronunciation:"라이트",meaning:"쓰다"},
{id:764,word:"wrong",pronunciation:"롱",meaning:"틀린"},
{id:765,word:"yard",pronunciation:"야드",meaning:"마당"},
{id:766,word:"year",pronunciation:"이어",meaning:"해, 연도"},
{id:767,word:"yellow",pronunciation:"옐로우",meaning:"노란색"},
{id:768,word:"yes",pronunciation:"예스",meaning:"예"},
{id:769,word:"yesterday",pronunciation:"예스터데이",meaning:"어제"},
{id:770,word:"yet",pronunciation:"옛",meaning:"아직"},
{id:771,word:"you",pronunciation:"유",meaning:"너, 당신"},
{id:772,word:"young",pronunciation:"영",meaning:"젊은"},
{id:773,word:"your",pronunciation:"유어",meaning:"너의"},
{id:774,word:"zebra",pronunciation:"지브라",meaning:"얼룩말"},
{id:775,word:"zero",pronunciation:"제로",meaning:"0"},
{id:776,word:"zoo",pronunciation:"주",meaning:"동물원"},
{id:777,word:"able",pronunciation:"에이블",meaning:"~할 수 있는"},
{id:778,word:"above",pronunciation:"어바브",meaning:"~위에"},
{id:779,word:"actor",pronunciation:"액터",meaning:"배우"},
{id:780,word:"add",pronunciation:"애드",meaning:"더하다"},
{id:781,word:"adventure",pronunciation:"어드벤처",meaning:"모험"},
{id:782,word:"advice",pronunciation:"어드바이스",meaning:"충고"},
{id:783,word:"alive",pronunciation:"얼라이브",meaning:"살아있는"},
{id:784,word:"almost",pronunciation:"올모스트",meaning:"거의"},
{id:785,word:"alone",pronunciation:"얼론",meaning:"혼자"},
{id:786,word:"already",pronunciation:"올레디",meaning:"이미"},
{id:787,word:"also",pronunciation:"올소",meaning:"또한"},
{id:788,word:"anything",pronunciation:"애니씽",meaning:"무엇이든"},
{id:789,word:"artist",pronunciation:"아티스트",meaning:"예술가"},
{id:790,word:"attention",pronunciation:"어텐션",meaning:"주의"},
{id:791,word:"beautifully",pronunciation:"뷰티풀리",meaning:"아름답게"},
{id:792,word:"believe",pronunciation:"빌리브",meaning:"믿다"},
{id:793,word:"best",pronunciation:"베스트",meaning:"가장 좋은"},
{id:794,word:"better",pronunciation:"베터",meaning:"더 좋은"},
{id:795,word:"both",pronunciation:"보우쓰",meaning:"둘 다"},
{id:796,word:"careful",pronunciation:"케어풀",meaning:"조심하는"},
{id:797,word:"carefully",pronunciation:"케어풀리",meaning:"조심스럽게"},
{id:798,word:"century",pronunciation:"센추리",meaning:"세기"},
{id:799,word:"certain",pronunciation:"서튼",meaning:"확실한"},
{id:800,word:"certainly",pronunciation:"서튼리",meaning:"확실히"}
];
